title: Git
author: 443cb49f-b30a-4e19-8c4a-fc72691de37d
updated_by: 443cb49f-b30a-4e19-8c4a-fc72691de37d
updated_at: 1730061230
blueprint: category
content: 'Master Git version control with tutorials on branching, merging, rebasing, and advanced workflows. Essential skills for modern development teams.'
