title: Ship30for30
author: 443cb49f-b30a-4e19-8c4a-fc72691de37d
updated_by: 443cb49f-b30a-4e19-8c4a-fc72691de37d
updated_at: 1730061245
blueprint: category
content: "Ship30for30 is an online writing challenge and course designed to help individuals create consistent content. Participants commit to “shipping” (publishing) short-form pieces of content for 30 consecutive days. The program strengthens consistency, overcomes writer's block, and helps individuals build online writing habits."
