title: Ship30for30
author: e721ea7d-a7b7-4257-9eaf-c54f259bb52b
updated_by: e721ea7d-a7b7-4257-9eaf-c54f259bb52b
updated_at: 1726364337
blueprint: category
content: "Ship30for30 is an online writing challenge and course designed to help individuals create consistent content. Participants commit to “shipping” (publishing) short-form pieces of content for 30 consecutive days. The program strengthens consistency, overcomes writer's block, and helps individuals build online writing habits."
