title: Statamic
author: 443cb49f-b30a-4e19-8c4a-fc72691de37d
updated_by: 443cb49f-b30a-4e19-8c4a-fc72691de37d
updated_at: 1730061249
blueprint: category
content: 'Statamic is a flexible, easy-to-use content management system (CMS) that simplifies complex workflows without relying on databases. It’s built with the popular PHP framework Laravel and offers robust features suitable for developers and marketers alike. It’s known for its fast performance and customizability.'
